amaranth-lang/amaranth-soc

- nmigen_soc/csr/bus.py
- nmigen_soc/csr/wishbone.py
- nmigen_soc/test/test_csr_bus.py
- nmigen_soc/test/test_wishbone_bus.py
- nmigen_soc/wishbone/bus.py
This PR adds support for extending the address space of a `MemoryMap`, after it has been instantiated.
Before this PR,  the `addr_width` parameter of a `csr.Multiplexer` would be the definitive address width of its underlying memory map.
This is inconvenient, because it forces the user to be aware of the size and address of each `csr.Element` that will be added to the multiplexer upfront.
```python3
from nmigen_soc import csr
mux = csr.Multiplexer(addr_width=2, data_width=8)
mux.add(csr.Element(8, "rw"))
mux.add(csr.Element(8, "rw"))
mux.add(csr.Element(8, "rw"))
```
This PR allows the address space covered by the `csr.Multiplexer` to be extended as resources are added to it.
```python3
mux = csr.Multiplexer(addr_width=1, data_width=8)
mux.add(csr.Element(8, "rw"), extend=True) …
```
> Add support for extending the address space of a memory map

- nmigen_soc/test/test_wishbone_bus.py
- nmigen_soc/wishbone/bus.py
> _Wednesday Jan 22, 2020 at 14:18 GMT_
> _Originally opened as [m-labs/nmigen-soc#3](https://github.com/m-labs/nmigen-soc/pull/3)_
> 
> This arbiter should be compatible with all the optional features of `wishbone.Interface`.
> 
> The round-robin implementation could perhaps be moved to `nmigen.lib` and imported back here, but that would make nmigen-soc depend on a later revision than nmigen v0.1.
> wishbone.bus: add Arbiter.

- nmigen_soc/csr/wishbone.py
- nmigen_soc/test/test_csr_wishbone.py
Before this commit, a CSR could be read two times in a single WB transaction.
Repro:
```python3
from nmigen import *
from nmigen.back.pysim import *
from nmigen_soc import csr
from nmigen_soc.memory import MemoryMap
from nmigen_soc.csr.wishbone import WishboneCSRBridge
csr_bus = csr.Interface(addr_width=2, data_width=8)
csr_bus.memory_map = MemoryMap(addr_width=2, data_width=8)
dut = WishboneCSRBridge(csr_bus, data_width=32)
def process():
yield dut.wb_bus.adr.eq(0x0)
yield dut.wb_bus.cyc.eq(1)
yield dut.wb_bus.stb.eq(1)
yield dut.wb_bus.sel.eq(0b0001)
yield
while not (yield dut.wb_bus.ack):
yield
yield dut.wb_bus.cyc.eq(0)
yield dut.wb_bus.stb.eq(0)
sim = Simulator(dut)
sim.add_clock(1e-6)
sim.add_sync_process(process)
with sim.write_vcd("repro.vcd"):
sim.run()
```
After this commit, …
> csr.wishbone: fix WishboneCSRBridge cycle counter.

- nmigen_soc/event.py
- nmigen_soc/test/test_event.py
Follow-up of #11, about decoupling event management from peripherals.
Events (represented by the `EventSource` class) can be gathered in an `InterruptSource` in order to generate interrupt requests. The interrupt source exposes an IRQ line, and is controlled by three CSRs: `status`, `pending` and `enable`.
> Add event management primitives

- nmigen_soc/test/test_csr_bus.py
- nmigen_soc/test/test_csr_wishbone.py
- nmigen_soc/test/test_event.py
- nmigen_soc/test/test_memory.py
- nmigen_soc/test/test_wishbone_bus.py
When functions support positional argument passing both passing the
argument by position and by keyword is part of the API. Using both call
methods in the unit tests for such arguments will detect possible future
backwards compatibility breakage.
> Test positional and keyword argument passing

- nmigen_soc/test/test_wishbone_bus.py
- nmigen_soc/wishbone/bus.py
Assume that bus may be arbitrated if lock feature is not present on
initiator. This assumption is added to the docstring.
> Use 0 as default for lock on subordinate bus

- nmigen_soc/periph.py
- nmigen_soc/test/test_periph.py
As suggested in https://github.com/nmigen/nmigen-soc/pull/11#issuecomment-602738198.
This PR proposes a `PeripheralInfo` class to gather the resources of a peripheral, with the aim of advertising them to the BSP generator. A `ConfigDict` class is also provided to collect constants.
> periph: add a PeripheralInfo class for metadata.

- nmigen_soc/periph.py
- nmigen_soc/test/test_periph.py
> periph: add a ConstantMap container for configuration constants.

- nmigen_soc/csr/wishbone.py
- nmigen_soc/test/test_csr_wishbone.py
Currently we ack for 2 cycles, even if in the second cycle stb and cyc
are not asserted. This could cause issues on a shared wishbone with
asynchronous cycle termination, because that ack would be interpreted
as completing the next transaction.
To avoid this just ack for 1 cycle only.
> csr.wishbone: Only ack for 1 cycle

- amaranth_soc/csr/bus.py
- tests/test_csr_bus.py
Before this commit, `csr.Multiplexer` had separate shadows for every element in its memory map. The same shadow was shared for read and write accesses to an `Element`; a combined read/write transaction was impossible despite being allowed by the CSR interface.
After this commit, `csr.Multiplexer` has separate shadows for read and write accesses, but both shadows are shared by every `Element` using them. For multiplexers with many elements, this approach also results in significant resource savings.
To measure the resource savings, let's consider this example:
```python3
from amaranth import *
from amaranth.back import rtlil
from amaranth_soc import csr
mux = csr.Multiplexer(addr_width=1, data_width=8, alignment=2)
for i in range(8):
a = csr.Element(32, "rw", name=f"a{i}")
mux.add(a, …
```
> csr.bus: redesign Multiplexer shadow registers.

- amaranth_soc/csr/bus.py
The former does int->float->int conversions, which gives incorrect results because Python uses 64-bit values to represent floats (e.g. `ceil(log2((1 << 64) + 1))` would return 64).
> csr.bus: replace ceil(log2(n)) with log2_int(n, need_pow2=False).

- amaranth_soc/csr/bus.py
- amaranth_soc/csr/event.py
- amaranth_soc/csr/wishbone.py
- amaranth_soc/memory.py
- amaranth_soc/wishbone/bus.py
* emphasize that `alignment` is a power-of-2 exponent;
* give default values of optional keyword arguments.
> Minor docstring clarifications.

- amaranth_soc/csr/bus.py
- amaranth_soc/csr/event.py
- amaranth_soc/csr/wishbone.py
- amaranth_soc/event.py
- amaranth_soc/wishbone/bus.py
- tests/test_csr_bus.py
- tests/test_csr_event.py
- tests/test_csr_wishbone.py
- tests/test_event.py
- tests/test_periph.py
- tests/test_wishbone_bus.py
Supersedes #48, as the changes to CSR and Wishbone are similar in nature, and would benefit from a common review.
> Migrate bus primitives to `amaranth.lib.wiring`

- amaranth_soc/csr/bus.py
- amaranth_soc/csr/event.py
- amaranth_soc/csr/wishbone.py
- amaranth_soc/event.py
- amaranth_soc/memory.py
- amaranth_soc/wishbone/bus.py
- tests/test_csr_bus.py
- tests/test_csr_event.py
- tests/test_csr_wishbone.py
- tests/test_event.py
- tests/test_memory.py
- tests/test_periph.py
- tests/test_wishbone_bus.py
These changes should conclude the migration of Amaranth SoC to `amaranth.lib.wiring`.
> Migrate elaboratables to lib.wiring components.

- amaranth_soc/wishbone/bus.py
- tests/test_wishbone_bus.py
This reverts commit 1b25700ed2a62ddf8d3733c6f5ee28b83c466d99.
Wishbone bus interfaces with 0-bit address widths are explicitly allowed by the specification, and may occur in some cases such as peripherals with FIFO-like interfaces.
> Revert "wishbone: restrict addr_width to positive integers."

- amaranth_soc/csr/bus.py
- amaranth_soc/event.py
- amaranth_soc/wishbone/bus.py
Due to Amaranth renaming its `Interface` class to `PureInterface` in commit https://github.com/amaranth-lang/amaranth/commit/0cdcab0fbbdd86390fd32105f695a164e0826ab8 importing anything that uses `wiring.Interface` fails. This commit introduces necessary renames to make it compatible with the latest Amaranth.
> Rename wiring.Interface to wiring.PureInterface

- amaranth_soc/csr/bus.py
- amaranth_soc/csr/event.py
- amaranth_soc/csr/wishbone.py
- amaranth_soc/event.py
- amaranth_soc/wishbone/bus.py
- tests/test_csr_bus.py
- tests/test_csr_event.py
- tests/test_event.py
- tests/test_wishbone_bus.py
Memory maps and event maps are now assigned to Interface objects instead of Signature objects (which can no longer hold mutable state), as things were before 9ffaf949.
See #62.
> Update to follow RFCs 37 and 38.

- amaranth_soc/csr/bus.py
Python sets have non-deterministic iteration, however dicts iterate in insertion order.
Ensuring the Shadow range set is iterated in a deterministic order causes chunks to be built in a deterministic order and thus chunks/registers to be processed in a deterministic order inside `elaborate()`.
If they are processed non-deterministically, then the Case ordering and various temporary variable names are produced non-deterministically, causing a non-deterministic final RTLIL output, which is undesirable.
Determinism is one of those things that's rather hard to prove true, but this nonetheless fixes a tested design's RTLIL output to be deterministic across all (several dozen) tested runs rather than be different almost every run.
> csr.bus: elaborate Multiplexer connections deterministically

- amaranth_soc/gpio.py
- tests/test_gpio.py
Remains in draft status until:
> Implement RFC 49: GPIO peripheral.

- amaranth_soc/csr/reg.py
- tests/test_csr_reg.py
Tested on my design and it works nice.
> Implement RFC 57: Single-Field Register Definition and Usage Shortcut

- amaranth_soc/memory.py
- tests/test_memory.py
- tests/test_wishbone_bus.py
As a breaking change, `MemoryMap.add_window(self, window, sparse=False)` will fail if `self.data_width // window.data_width` isn't a power-of-2 or is greater than `2 ** window.alignment`.
> memory: fix address translation of resources located in dense windows.

- amaranth_soc/csr/bus.py
- amaranth_soc/csr/reg.py
- amaranth_soc/event.py
- amaranth_soc/wishbone/bus.py
- tests/test_csr_bus.py
- tests/test_wishbone_bus.py
Since RFC 38, the signature of a component can only be assigned within its constructor. It is no longer useful to decouple the validation of signature parameters from its constructor.
> Remove .check_parameters() method from signatures.

- amaranth_soc/csr/bus.py
- amaranth_soc/csr/event.py
- amaranth_soc/csr/reg.py
- amaranth_soc/csr/wishbone.py
- amaranth_soc/gpio.py
- amaranth_soc/memory.py
- amaranth_soc/wishbone/bus.py
- tests/test_csr_bus.py
- tests/test_csr_reg.py
- tests/test_memory.py
> Implement RFC 70: unify naming of `MemoryMap` resources and windows.

- amaranth_soc/wishbone/sram.py
- tests/test_wishbone_sram.py
`WishboneSRAM` can never service a read and a write request at the same time, so it's possible to improve support for SPRAM by disabling the read port when the write-enable is set.
This stops interfering with SPRAM inference where the underlying `Memory` primitive could otherwise match one.
> WishboneSRAM support for single-port RAM
